server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:root.db
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    # druid相关配置
    druid:
    # 连接池初始化大小
    initial-size: 8
    # 最大活跃连接数
    max-active: 20
    # 最小空闲连接数
    min-idle: 1
    # 获取连接等待超时的时间
    max-wait: 60000
    # 间隔多久才进行一次检测，检测需要关闭的空闲连接，ms
    time-between-eviction-runs-millis: 60000
    validation-query: select 'x'
    # 配置过滤器，https://github.com/alibaba/druid/wiki/%E5%86%85%E7%BD%AEFilter%E7%9A%84%E5%88%AB%E5%90%8D
    filters: stat,slf4j,config
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
